# Generated by Django 4.2.1 on 2023-07-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_category_alter_room_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descriptions',
            new_name='description',
        ),
    ]
