# Generated by Django 4.2.1 on 2023-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_category_alter_experience_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='perks',
            field=models.ManyToManyField(to='experiences.perk'),
        ),
    ]
