# Generated by Django 4.2.1 on 2023-07-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_amenities'),
        ('experiences', '0005_alter_experience_perks'),
        ('wishlists', '0003_alter_wishlist_experiences_alter_wishlist_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='experiences',
            field=models.ManyToManyField(null=True, related_name='wishlists', to='experiences.experience'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='rooms.room'),
        ),
    ]
